Vagrant.configure("2") do |config|
  config.vm.box = "RedHatAugust/WinterMute-Neuromancer"
  config.vm.base_mac = "0800274F1C05"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "haymarketers2", adapter: "1"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "this_should_not_exist_and_is_only_a_filler", adapter: "2"
end
