Vagrant.configure("2") do |config|
  config.vm.box = "RedHatAugust/dev-random-relativity-v1.0.1"
  config.vm.base_mac = "080027D9C7E0"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "haymarketers", adapter: "1"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "this_should_not_exist_and_is_only_a_filler", adapter: "2"
end
