Vagrant.configure("2") do |config|
  config.vm.box = "RedHatAugust/Doomsday-CTF-Control-Server"
  config.vm.base_mac = "0800273092A5"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "haymarketers", adapter: "1"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "this_should_not_exist_and_is_only_a_filler", adapter: "2"
end
Vagrant.configure("2") do |config|
  config.vm.box = "RedHatAugust/Doomsday-CTF-Doomsday-Server"
  config.vm.base_mac = "080027C4FB18"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "haymarketers", adapter: "1"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "this_should_not_exist_and_is_only_a_filler", adapter: "2"
end
