Vagrant.configure("2") do |config|
  config.vm.box = "RedHatAugust/Photographer-1"
  config.vm.base_mac = "0800277EC90B"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "haymarketers", adapter: "1"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "haymarketers", adapter: "2"
end
