Vagrant.configure("2") do |config|
  config.vm.box = "RedHatAugust/MoneyHeist-Catch-Us-If-You-Can"
  config.vm.base_mac = "0800271ADBB8"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "haymarketers", adapter: "1"
  config.vm.network "private_network", type: "dhcp", virtualbox__intnet: "this_should_not_exist_and_is_only_a_filler", adapter: "2"
end
